import * as vscode from 'vscode';

export interface LLMProvider {
    generateCode(prompt: string): Promise<string>;
}

export class OllamaProvider implements LLMProvider {
    private model: string;
    
    constructor(model: string = 'llama3') {
        this.model = model;
    }

    async generateCode(prompt: string): Promise<string> {
        vscode.window.showInformationMessage(`Calling local offline model: ${this.model}...`);
        try {
            // Using Node's native fetch
            const response = await fetch('http://localhost:11434/api/generate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    model: this.model,
                    prompt: prompt,
                    stream: false
                })
            });
            
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            
            const data = await response.json() as any;
            return data.response;
        } catch (error) {
            vscode.window.showErrorMessage('Offline model connection failed. Please ensure Ollama is running on localhost:11434');
            return '';
        }
    }
}

export class GeminiProvider implements LLMProvider {
    private projectId: string;

    constructor(projectId: string = 'project-94c754bc-315e-4ed0-b25') {
        this.projectId = projectId;
    }

    async generateCode(prompt: string): Promise<string> {
        vscode.window.showInformationMessage(`Calling Gemini via Google Cloud (Project: ${this.projectId})...`);
        // In a full implementation, we'd use the Vertex AI SDK here.
        // For the prototype, we return a mock response that the Telolexic Auditor will verify.
        return "// Generated by Gemini\nconst x = 10;\nreturn x;";
    }
}
